name: ulid
description: >
  Lexicographically sortable, 128-bit identifier (UUID) with 48-bit timestamp and 80 random bits.
  Canonically encoded as a 26 character string, as opposed to the 36 character UUID.
version: 1.1.0
homepage: https://github.com/agilord/ulid

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
